'use strict';
const room=document.getElementById('room'),feedButton=document.getElementById('feedButton'),feedLabel=document.getElementById('feedLabel'),resetButton=document.getElementById('resetButton'),soundToggle=document.getElementById('soundToggle'),hand=document.getElementById('foodHand'),statusText=document.getElementById('status'),sceneState=document.getElementById('sceneState'),sceneCaption=document.getElementById('sceneCaption');
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const pets=[{el:document.getElementById('doudi'),name:'豆弟',row:0,home:[35,65],phase:0},{el:document.getElementById('dongdi'),name:'咚地',row:1,home:[65,68],phase:Math.PI}];
let active=false,started=0,shakeUntil=0,muted=false,audio=null,noiseBuffer=null,lastSound=0,lastFrame=0,hiddenAt=0,ready=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const smooth=t=>t*t*(3-2*t);
function initAudio(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!audio){audio=new AC();const length=audio.sampleRate*.09;noiseBuffer=audio.createBuffer(1,length,audio.sampleRate);const samples=noiseBuffer.getChannelData(0);for(let i=0;i<length;i++)samples[i]=(Math.random()*2-1)*Math.exp(-i/(length*.16));}if(audio.state==='suspended')audio.resume().catch(()=>{statusText.textContent='声音还没唤醒，再点一下喂饭啦。'});return true;}catch{return false;}}
function pelletSound(){if(muted||!audio||audio.state!=='running')return;const now=audio.currentTime;for(let i=0;i<8;i++){const t=now+i*.011+Math.random()*.009;const source=audio.createBufferSource();source.buffer=noiseBuffer;source.playbackRate.value=.7+Math.random()*.9;const filter=audio.createBiquadFilter();filter.type='bandpass';filter.frequency.value=1100+Math.random()*2000;filter.Q.value=.75;const gain=audio.createGain();gain.gain.value=.1+Math.random()*.08;source.connect(filter).connect(gain).connect(audio.destination);source.start(t);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}const osc=audio.createOscillator(),g=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(620+Math.random()*180,now);g.gain.setValueAtTime(.025,now);g.gain.exponentialRampToValueAtTime(.001,now+.055);osc.connect(g).connect(audio.destination);osc.start(now);osc.stop(now+.06);osc.onended=()=>{osc.disconnect();g.disconnect();};}
function feed(){if(!ready)return {state:'loading'};initAudio();const now=performance.now();if(!active){active=true;started=now;pets.forEach(p=>p.angle=p.phase);}shakeUntil=now+2600;lastSound=0;room.classList.add('active');feedLabel.textContent='再摇一摇';resetButton.hidden=false;sceneState.textContent='晚饭铃响啦';sceneCaption.textContent='耳朵一动，快乐就开始了。';statusText.textContent=muted?'听见啦！两团毛球已经出发。':'沙沙一响，整个地毯都热闹起来。';return {state:'excited',rabbits:['豆弟','咚地']};}
function rest(){active=false;room.classList.remove('active');hand.classList.remove('shaking');feedLabel.textContent='喂饭啦';resetButton.hidden=true;sceneState.textContent='安静的晚间';sceneCaption.textContent='两团毛茸茸，正在发呆。';statusText.textContent='一听到这个声音，就藏不住开心。';return {state:'resting'};}
feedButton.addEventListener('click',feed);resetButton.addEventListener('click',rest);
soundToggle.addEventListener('click',()=>{muted=!muted;soundToggle.setAttribute('aria-pressed',String(!muted));soundToggle.setAttribute('aria-label',muted?'打开声音':'关闭声音');if(!muted){initAudio();if(active)pelletSound();}});
function pose(p,col,x,y,flip,bob,tilt,scale){p.el.style.left=x+'%';p.el.style.top=y+'%';p.el.style.zIndex=String(Math.round(y));const sprite=p.el.querySelector('.rabbit-sprite');sprite.style.backgroundPosition=(col*50)+'% '+(p.row*100)+'%';sprite.style.clipPath=col===2?'inset(0 0 0 6%)':'none';p.el.querySelector('.rabbit-body').style.transform=`translateY(${bob}px) rotate(${tilt}deg) scale(${flip*scale},${scale})`;p.el.querySelector('.rabbit-shadow').style.opacity=String(clamp(1+bob*.045,.35,1));p.el.classList.toggle('looking',col===2&&active);p.el.setAttribute('aria-label',p.name+(col===0?'正在地毯上休息':col===1?'开心地绕着地毯跑圈':'站起来寻找兔粮'));}
function frame(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;if(!document.hidden){const elapsed=(now-started)/1000;const shaking=active&&(now<shakeUntil||elapsed%8<1.15);hand.classList.toggle('shaking',shaking);if(shaking&&now-lastSound>175){pelletSound();lastSound=now;}pets.forEach((p,i)=>{if(!active){const breath=reducedMotion?1:1+Math.sin(now/1250+i)*.012;pose(p,0,p.home[0],p.home[1],1,0,0,breath);p.el.querySelector('.thought').textContent=i?'z z z':'呼…';return;}const local=elapsed+(i?3.1:0);const cycle=local%9.1;const looking=(elapsed<.8)||(cycle>5.9&&cycle<7.7);if(!looking)p.angle+=dt*(reducedMotion?.34:1.22);const radiusX=reducedMotion?15:24;const x=50+Math.cos(p.angle)*radiusX,y=65+Math.sin(p.angle)*10;const enter=smooth(clamp(elapsed/1.1,0,1));const px=p.home[0]+(x-p.home[0])*enter,py=p.home[1]+(y-p.home[1])*enter;const flip=looking?1:(-Math.sin(p.angle)>=0?1:-1);const bounce=looking?Math.sin(now/350+i)*.9:-(Math.abs(Math.sin(now/110+i))* (reducedMotion?2:9));pose(p,looking?2:1,px,py,flip,bounce,looking?0:Math.sin(now/120+i)*2,1+(py-65)*.008);p.el.querySelector('.thought').textContent=i?'兔粮在哪里？':'是开饭了吗？';});if(active&&elapsed>28)rest();}requestAnimationFrame(frame);}
document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenAt=performance.now();if(audio?.state==='running')audio.suspend();}else{if(active){const gap=performance.now()-hiddenAt;started+=gap;shakeUntil+=gap;}if(audio&&!muted)audio.resume().catch(()=>{});}});
const assetUrls=['assets/room.png','assets/rabbits.png','assets/hand.png'];
Promise.all(assetUrls.map(src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=()=>reject(new Error(src));img.src=src;}))).then(()=>{ready=true;document.getElementById('loading').classList.add('ready');requestAnimationFrame(frame);}).catch(()=>{const loading=document.getElementById('loading');loading.textContent='图片还没加载好，请刷新再试一次。';});
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();for(const [name,title,fn]of[['start_feeding','喂饭啦',feed],['rest_rabbits','让兔子休息',rest]]){try{Promise.resolve(context.registerTool({name,title,description:name==='start_feeding'?'显示并摇动半杯兔粮，让豆弟和咚地开心地跑圈和站起张望。':'收起量杯，让两只兔子回到地毯上休息。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('此操作不接受参数');return fn();}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
